import { IOrder } from "@/types/IOrder";
import { freelancers } from "./links.data";

export const orders: IOrder[] = [
    {
        category: 'design',
        description: 'vejijr ubguehbduifwueiqojadhfuehabj kwndqouifodgbvuijs chbuidkshfvubeikajdskcnvubyaeincv yufsbdcihajohucdisj',
        documents: ['grewgre', 'fer', 'ifrnwlkdsma'],
        id: 1,
        owner: freelancers[0],
        price: 20000,
        createdAt: '01.01.2015',
        timeFrame: '11.01.2015',
        title: 'Нужно сделать Дизайн сайта по тематике авто ',
        offers: 6
    },
    {
        category: 'design',
        createdAt: '01.01.2015',
        description: 'vejijr ubguehbduifwueiqojadhfuehabj kwndqouifodgbvuijs chbuidkshfvubeikajdskcnvubyaeincv yufsbdcihajohucdisj',
        documents: ['grewgre', 'fer', 'ifrnwlkdsma'],
        id: 2,
        owner: freelancers[0],
        price: 20000,
        timeFrame: 4,
        title: 'Нужно сделать Дизайн сайта по тематике авто ',
    },
    {
        category: 'design',
        createdAt: '01.01.2015',
        description: 'vejijr ubguehbduifwueiqojadhfuehabj kwndqouifodgbvuijs chbuidkshfvubeikajdskcnvubyaeincv yufsbdcihajohucdisj',
        documents: ['grewgre', 'fer', 'ifrnwlkdsma'],
        id: 3,
        owner: freelancers[0],
        price: 20000,
        timeFrame: 4,
        title: 'Нужно сделать Дизайн сайта по тематике авто ',
    },
    {
        category: 'design',
        createdAt: '01.01.2015',
        description: 'vejijr ubguehbduifwueiqojadhfuehabj kwndqouifodgbvuijs chbuidkshfvubeikajdskcnvubyaeincv yufsbdcihajohucdisj',
        documents: ['grewgre', 'fer', 'ifrnwlkdsma'],
        id: 4,
        owner: freelancers[0],
        price: 20000,
        timeFrame: 4,
        title: 'Нужно сделать Дизайн сайта по тематике авто ',
    },
    {
        category: 'design',
        createdAt: '01.01.2015',
        description: 'vejijr ubguehbduifwueiqojadhfuehabj kwndqouifodgbvuijs chbuidkshfvubeikajdskcnvubyaeincv yufsbdcihajohucdisj',
        documents: ['grewgre', 'fer', 'ifrnwlkdsma'],
        id: 5,
        owner: freelancers[0],
        price: 20000,
        timeFrame: 4,
        title: 'Нужно сделать Дизайн сайта по тематике авто ',
    },
]